baseURL = 'https://www.xdcyw.net/'
languageCode = 'ja'
title = 'xdcyw.net'

[params]
  description = "札幌在住の多重人格（解離性同一性障害）当事者が司法試験を目指す過程と日常を綴るブログ。法律学習やメンタルヘルス、ITについて発信します。"
  ogDefaultImage = "/ChatGPT Image 2025年9月29日 07_10_21.png"
  adsenseClient = ""
  authorName = "xdcyw"
  alternateName = "Fuyuki"
  twitterSite = "@xdcyw_"
  twitterCreator = "@xdcyw_"
  sameAs = [
    "https://x.com/xdcyw_",
    "https://note.com/ncc1030"
  ]

[taxonomies]
  category = "categories"
  tag = "tags"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "profile"
    url = "/about/"
    weight = 5
  [[menu.main]]
    identifier = "posts"
    name = "posts"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "categories"
    name = "categories"
    url = "/categories/"
    weight = 20
  [[menu.main]]
    identifier = "privacy"
    name = "privacy"
    url = "/privacy/"
    weight = 30

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
